// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  company_name, 
  contact_name, 
  email, 
  phone, 
  address_line1, 
  address_line2,
  city,
  province,
  postal_code,
  country)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_name, contact_name, email, phone, address_line1, address_line2, city, province, postal_code, country, notes, user_id, created_at, updated_at, deleted_at
`

type CreateCustomerParams struct {
	CompanyName  pgtype.Text
	ContactName  string
	Email        string
	Phone        string
	AddressLine1 string
	AddressLine2 pgtype.Text
	City         string
	Province     string
	PostalCode   string
	Country      pgtype.Text
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :exec
UPDATE customers
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCustomer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomer, id)
	return err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, company_name, contact_name, email, phone, address_line1, address_line2, city, province, postal_code, country, notes, user_id, created_at, updated_at, deleted_at FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT id, company_name, contact_name, email, phone, address_line1, address_line2, city, province, postal_code, country, notes, user_id, created_at, updated_at, deleted_at FROM customers
`

func (q *Queries) GetCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.Province,
			&i.PostalCode,
			&i.Country,
			&i.Notes,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET company_name = $2, 
    contact_name = $3, 
    email = $4, 
    phone = $5, 
    address_line1 = $6, 
    address_line2 = $7, 
    city = $8, 
    province = $9, 
    postal_code = $10,
    country = $11,
    notes = $12,
    user_id = $13,
    updated_at = NOW()
WHERE id = $1
RETURNING id, company_name, contact_name, email, phone, address_line1, address_line2, city, province, postal_code, country, notes, user_id, created_at, updated_at, deleted_at
`

type UpdateCustomerParams struct {
	ID           uuid.UUID
	CompanyName  pgtype.Text
	ContactName  string
	Email        string
	Phone        string
	AddressLine1 string
	AddressLine2 pgtype.Text
	City         string
	Province     string
	PostalCode   string
	Country      pgtype.Text
	Notes        pgtype.Text
	UserID       *uuid.UUID
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.CompanyName,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.Province,
		arg.PostalCode,
		arg.Country,
		arg.Notes,
		arg.UserID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Province,
		&i.PostalCode,
		&i.Country,
		&i.Notes,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
