// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory_items (sku, name, description, category, unit_price, quantity_in_stock, reorder_threshold, supplier_name, supplier_contact)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, sku, name, description, category, unit_price, quantity_in_stock, reorder_threshold, supplier_name, supplier_contact, is_active, created_at, updated_at
`

type CreateInventoryItemParams struct {
	Sku              string
	Name             string
	Description      pgtype.Text
	Category         pgtype.Text
	UnitPrice        pgtype.Numeric
	QuantityInStock  int32
	ReorderThreshold int32
	SupplierName     pgtype.Text
	SupplierContact  pgtype.Text
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.UnitPrice,
		arg.QuantityInStock,
		arg.ReorderThreshold,
		arg.SupplierName,
		arg.SupplierContact,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.UnitPrice,
		&i.QuantityInStock,
		&i.ReorderThreshold,
		&i.SupplierName,
		&i.SupplierContact,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventory = `-- name: GetInventory :many
SELECT id, sku, name, description, category, unit_price, quantity_in_stock, reorder_threshold, supplier_name, supplier_contact, is_active, created_at, updated_at FROM inventory_items
`

func (q *Queries) GetInventory(ctx context.Context) ([]InventoryItem, error) {
	rows, err := q.db.Query(ctx, getInventory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InventoryItem
	for rows.Next() {
		var i InventoryItem
		if err := rows.Scan(
			&i.ID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.UnitPrice,
			&i.QuantityInStock,
			&i.ReorderThreshold,
			&i.SupplierName,
			&i.SupplierContact,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryItemBySKU = `-- name: GetInventoryItemBySKU :one
SELECT id, sku, name, description, category, unit_price, quantity_in_stock, reorder_threshold, supplier_name, supplier_contact, is_active, created_at, updated_at FROM inventory_items
WHERE sku = $1
`

func (q *Queries) GetInventoryItemBySKU(ctx context.Context, sku string) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, getInventoryItemBySKU, sku)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.UnitPrice,
		&i.QuantityInStock,
		&i.ReorderThreshold,
		&i.SupplierName,
		&i.SupplierContact,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory_items
SET name = $2, 
    description = $3, 
    category = $4, 
    unit_price = $5, 
    quantity_in_stock = $6, 
    reorder_threshold = $7, 
    supplier_name = $8, 
    supplier_contact = $9, 
    is_active = $10,
    updated_at = NOW()
WHERE sku = $1
RETURNING id, sku, name, description, category, unit_price, quantity_in_stock, reorder_threshold, supplier_name, supplier_contact, is_active, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	Sku              string
	Name             string
	Description      pgtype.Text
	Category         pgtype.Text
	UnitPrice        pgtype.Numeric
	QuantityInStock  int32
	ReorderThreshold int32
	SupplierName     pgtype.Text
	SupplierContact  pgtype.Text
	IsActive         pgtype.Bool
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.UnitPrice,
		arg.QuantityInStock,
		arg.ReorderThreshold,
		arg.SupplierName,
		arg.SupplierContact,
		arg.IsActive,
	)
	var i InventoryItem
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.UnitPrice,
		&i.QuantityInStock,
		&i.ReorderThreshold,
		&i.SupplierName,
		&i.SupplierContact,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
