// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64
	UserID    *uuid.UUID
	Action    string
	TableName string
	RecordID  *uuid.UUID
	OldValues []byte
	NewValues []byte
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type Customer struct {
	ID           uuid.UUID
	CompanyName  pgtype.Text
	ContactName  string
	Email        string
	Phone        string
	AddressLine1 string
	AddressLine2 pgtype.Text
	City         string
	Province     string
	PostalCode   string
	Country      pgtype.Text
	Notes        pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type InventoryItem struct {
	ID               uuid.UUID
	Sku              string
	Name             string
	Description      pgtype.Text
	Category         pgtype.Text
	UnitPrice        pgtype.Numeric
	QuantityInStock  int32
	ReorderThreshold int32
	SupplierName     pgtype.Text
	SupplierContact  pgtype.Text
	IsActive         pgtype.Bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Invoice struct {
	ID            uuid.UUID
	InvoiceNumber string
	JobID         uuid.UUID
	CustomerID    uuid.UUID
	Subtotal      pgtype.Numeric
	TaxRate       pgtype.Numeric
	TaxAmount     pgtype.Numeric
	Status        string
	DueDate       pgtype.Date
	IssuedDate    pgtype.Date
	PaidDate      pgtype.Date
	PaymentMethod pgtype.Text
	Notes         pgtype.Text
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Job struct {
	ID                   uuid.UUID
	JobNumber            string
	CustomerID           uuid.UUID
	AssignedTechnicianID *uuid.UUID
	Title                string
	Description          pgtype.Text
	Status               string
	Priority             pgtype.Text
	ScheduledStart       pgtype.Timestamptz
	ScheduledEnd         pgtype.Timestamptz
	ActualStart          pgtype.Timestamptz
	ActualEnd            pgtype.Timestamptz
	ServiceAddressLine1  string
	ServiceAddressLine2  pgtype.Text
	ServiceCity          string
	ServiceProvince      string
	ServicePostalCode    string
	Notes                pgtype.Text
	InternalNotes        pgtype.Text
	CreatedBy            *uuid.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
}

type JobLabor struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	TechnicianID uuid.UUID
	HoursWorked  pgtype.Numeric
	HourlyRate   pgtype.Numeric
	Subtotal     pgtype.Numeric
	Description  pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type JobPart struct {
	ID              uuid.UUID
	JobID           uuid.UUID
	InventoryItemID uuid.UUID
	QuantityUsed    int32
	UnitPriceAtUse  pgtype.Numeric
	Subtotal        pgtype.Numeric
	Notes           pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type Role struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	Phone        pgtype.Text
	IsActive     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type UserRole struct {
	UserID uuid.UUID
	RoleID int32
}
