// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        int64
	UserID    uuid.NullUUID
	Action    string
	TableName string
	RecordID  uuid.NullUUID
	OldValues pqtype.NullRawMessage
	NewValues pqtype.NullRawMessage
	IpAddress sql.NullString
	UserAgent sql.NullString
	CreatedAt sql.NullTime
}

type Customer struct {
	ID           uuid.UUID
	CompanyName  sql.NullString
	ContactName  string
	Email        string
	Phone        string
	AddressLine1 string
	AddressLine2 sql.NullString
	City         string
	Province     string
	PostalCode   string
	Country      sql.NullString
	Notes        sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type InventoryItem struct {
	ID               uuid.UUID
	Sku              string
	Name             string
	Description      sql.NullString
	Category         sql.NullString
	UnitPrice        string
	QuantityInStock  int32
	ReorderThreshold int32
	SupplierName     sql.NullString
	SupplierContact  sql.NullString
	IsActive         sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Invoice struct {
	ID            uuid.UUID
	InvoiceNumber string
	JobID         uuid.UUID
	CustomerID    uuid.UUID
	Subtotal      string
	TaxRate       sql.NullString
	TaxAmount     sql.NullString
	Status        string
	DueDate       time.Time
	IssuedDate    time.Time
	PaidDate      sql.NullTime
	PaymentMethod sql.NullString
	Notes         sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type Job struct {
	ID                   uuid.UUID
	JobNumber            string
	CustomerID           uuid.UUID
	AssignedTechnicianID uuid.NullUUID
	Title                string
	Description          sql.NullString
	Status               string
	Priority             sql.NullString
	ScheduledStart       time.Time
	ScheduledEnd         sql.NullTime
	ActualStart          sql.NullTime
	ActualEnd            sql.NullTime
	ServiceAddressLine1  string
	ServiceAddressLine2  sql.NullString
	ServiceCity          string
	ServiceProvince      string
	ServicePostalCode    string
	Notes                sql.NullString
	InternalNotes        sql.NullString
	CreatedBy            uuid.NullUUID
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	DeletedAt            sql.NullTime
}

type JobLabor struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	TechnicianID uuid.UUID
	HoursWorked  string
	HourlyRate   string
	Subtotal     sql.NullString
	Description  sql.NullString
	CreatedAt    sql.NullTime
}

type JobPart struct {
	ID              uuid.UUID
	JobID           uuid.UUID
	InventoryItemID uuid.UUID
	QuantityUsed    int32
	UnitPriceAtUse  string
	Subtotal        sql.NullString
	Notes           sql.NullString
	CreatedAt       sql.NullTime
}

type Role struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FirstName    string
	LastName     string
	Phone        sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserRole struct {
	UserID uuid.UUID
	RoleID int32
}
