// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserRoles = `-- name: CreateUserRoles :one
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
RETURNING user_id, role_id
`

type CreateUserRolesParams struct {
	UserID uuid.UUID
	RoleID int32
}

func (q *Queries) CreateUserRoles(ctx context.Context, arg CreateUserRolesParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, createUserRoles, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(&i.UserID, &i.RoleID)
	return i, err
}
