// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserRoles = `-- name: CreateUserRoles :one
WITH inserted_user_roles AS (
  INSERT INTO user_roles (user_id, role_id)
  VALUES ($1, $2)
  RETURNING user_id, role_id
)
SELECT inserted_user_roles.user_id, inserted_user_roles.role_id, roles.name AS role_name
FROM inserted_user_roles
INNER JOIN roles ON roles.id = inserted_user_roles.role_id
`

type CreateUserRolesParams struct {
	UserID uuid.UUID
	RoleID int32
}

type CreateUserRolesRow struct {
	UserID   uuid.UUID
	RoleID   int32
	RoleName string
}

func (q *Queries) CreateUserRoles(ctx context.Context, arg CreateUserRolesParams) (CreateUserRolesRow, error) {
	row := q.db.QueryRow(ctx, createUserRoles, arg.UserID, arg.RoleID)
	var i CreateUserRolesRow
	err := row.Scan(&i.UserID, &i.RoleID, &i.RoleName)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT roles.name FROM user_roles
INNER JOIN roles ON roles.id = role_id
WHERE user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
